default_context:
  project_name: 'bookstore'
  project_slug: 'bookstore'
  domain_main: 'libreria.biz'
  domain_staging: 'stag.libreria.biz'
  docker_swarm_stack_name_main: 'libreria-biz'
  docker_swarm_stack_name_staging: 'stag-libreria-biz'
  secret_key: '64e5da5a359a6821de494d8bd96f035c467875e8947e8ac1646d45e1c77be3f1'
  first_superuser: 'admin@libreria.biz'
  first_superuser_password: 'cd0fea5dd04c9aab2119be7018519dbef92a9de06819be13162c7593f0282175'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.libreria.biz", "https://stag.libreria.biz", "https://libreria.biz", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.mailgun.org'
  smtp_user: 'postmaster@sandboxfc4d75a23bc140348be571a6729da209.mailgun.org'
  smtp_password: '6a48b9bc522f5d9d06907ad0d73e9c98-b2f5ed24-df6c8eeb'
  smtp_emails_from_email: 'info@libreria.biz'
  postgres_password: 'password'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'cd0fea5dd04c9aab2119be7018519dbef92a9de06819be13162c7593f0282175'
  traefik_constraint_tag: 'libreria.biz'
  traefik_constraint_tag_staging: 'stag.libreria.biz'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:cd0fea5dd04c9aab2119be7018519dbef92a9de06819be13162c7593f0282175'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
